### ISSUE TITLE
Bug to Trello extension not working

### ISSUE THREAD

**Issue by irshadis** [andrewsomething/bug2trello#15]
Hello,
I using Bugzilla 4.2 version. I search for a bug and then click on the Bug to Trello extension, select the board and the list, click on Add to Trello button. It is not adding that bug to Trello board. Let me know if this is due to version incompatibility or I am missing out something here.
Thanks,
Irshad

**Comment by andrewsomething** [comment]
Bugzilla support currently requires that the JSON-RPC interface is available. So not all instances are supported.
