### ISSUE TITLE
`undefined (Issue)` card is created when I use version 0.7

### ISSUE THREAD

**Issue by bakorer** [andrewsomething/bug2trello#22]
Hi, Thank you for updating the bug2trello chrome extension.
But I found the bug.

If I clicked the `Add to Trello` button, the card is created with title `com: #25099 - undefined (Issue)`.
It seems lacking the pull request title.

![image](https://cloud.githubusercontent.com/assets/844012/25891785/3eeb1cd4-35ad-11e7-9065-0611b39db93b.png)

![image](https://cloud.githubusercontent.com/assets/844012/25891975/de8aba24-35ad-11e7-8755-544663ba097b.png)

Could you fix this bug if you can?

I'm using version 0.7.

![image](https://cloud.githubusercontent.com/assets/844012/25892028/0f21ed88-35ae-11e7-87f0-d5f6e78bf507.png)

Thanks!

**Comment by andrewsomething** [comment]
Thanks for the report. What platform is the bug/issue on?

**Comment by kongo** [comment]
Encountered the same issue with Bitbucket.

**Comment by bakorer** [comment]
@andrewsomething 

> What platform is the bug/issue on?

the info is below.

- github private repository
  - the url is pull-request url
- Chrome Version 58.0.3029.110 (64-bit)
- macOS

![image](https://cloud.githubusercontent.com/assets/844012/26347012/0504fac2-3fe3-11e7-86d0-f3cbab0e536d.png)

**Comment by bakorer** [comment]
I check-outed the old version 0.6 and I'm using it now.

**Comment by eoger** [comment]
I just committed a fix (https://github.com/andrewsomething/bug2trello/commit/ae9a8e746c1afe4901c874b7ad1d89c1e0620902) for that issue on master, could you try and see if this resolves the problem for you @bakorer @kongo?

**Comment by shige** [comment]
@eoger CC: @kongo Thank you for fixing this problem. 👏 

I checked on the current master branch ( ae9a8e746c1afe4901c874b7ad1d89c1e0620902 ) , but it seems some errors on chrome developer tools. 👀 

Could you check these errors ❓ 

![image](https://user-images.githubusercontent.com/844012/28636469-1796bc24-71f3-11e7-856f-7434827efa1e.png)

```
index.js Failed to load resource: net::ERR_FILE_NOT_FOUND
client.js:11 Uncaught ReferenceError: jQuery is not defined
    at client.js:11
```

**Comment by eoger** [comment]
I had the same problem, it seems that npm run dev is broken. Run npm run build and load the temporary addon from dist/

**Comment by shige** [comment]
@eoger Thanks! 
Which Node.js version should I use?

**Comment by eoger** [comment]
I think as long as it's recent it's fine. I used node 8 to work on that patch.

**Comment by shige** [comment]
@eoger It works on GitHub private issue and pull-request. 👏 

----

📝 Tried following

```sh
nvm install v8.2.1
npm install
npm run build
```

Load dist dir via Chrome browser.

**Comment by eoger** [comment]
Awesome, thank you for testing!

**Comment by shige** [comment]
It seems fixed on current master https://github.com/andrewsomething/bug2trello/commit/ae9a8e746c1afe4901c874b7ad1d89c1e0620902
